spring:
  application:
    name: document_store
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  mvc:
    problemdetails:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:9090/realms/IAM
server:
    port: 8084
