services:
    springapp:
      container_name: iam
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - 'SPRING_PROFILES_ACTIVE=prod'
      ports:
        - '8080:8080'
      depends_on:
        - keycloak
      network_mode: host
      extra_hosts:
        - "host.docker.internal:host-gateway"
    keycloak:
      image: keycloak/keycloak:25.0.4
      container_name: keycloak
      ports:
        - '9090:8080'
      environment:
         - "KEYCLOAK_ADMIN: admin"
         - "KEYCLOAK_ADMIN_PASSWORD: password"
      volumes:
        - keycloak-data:/opt/keycloak/data
      command: start-dev
      networks:
        - kfk-net
volumes:
  keycloak-data:
networks:
  kfk-net:
    name: kfk-net
    external: true
