services:
  keycloak:
    container_name: keycloak
    image: keycloak/keycloak:25.0.4
    ports:
      - '9090:8080'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    volumes:
      - keycloak-data:/opt/keycloak/data
    command: start-dev
    networks:
      - kfk-net
volumes:
  keycloak-data:
networks:
  kfk-net:
    name: kfk-net
    external: true