/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as AuthIndexImport } from './routes/_auth/index'
import { Route as AuthSkillsIndexImport } from './routes/_auth/skills/index'
import { Route as AuthMessageIndexImport } from './routes/_auth/message/index'
import { Route as AuthJoboffersIndexImport } from './routes/_auth/joboffers/index'
import { Route as AuthContactsIndexImport } from './routes/_auth/contacts/index'
import { Route as AuthSkillsAddIndexImport } from './routes/_auth/skills/add/index'
import { Route as AuthJoboffersAddIndexImport } from './routes/_auth/joboffers/add/index'
import { Route as AuthJoboffersIdIndexImport } from './routes/_auth/joboffers/$id/index'
import { Route as AuthContactsAddIndexImport } from './routes/_auth/contacts/add/index'
import { Route as AuthContactsIdIndexImport } from './routes/_auth/contacts/$id/index'
import { Route as AuthSkillsIdEditIndexImport } from './routes/_auth/skills/$id/edit/index'
import { Route as AuthJoboffersIdEditIndexImport } from './routes/_auth/joboffers/$id/edit/index'
import { Route as AuthContactsIdEditIndexImport } from './routes/_auth/contacts/$id/edit/index'
import { Route as AuthJoboffersIdEditStatusIndexImport } from './routes/_auth/joboffers/$id/edit/status/index'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSkillsIndexRoute = AuthSkillsIndexImport.update({
  path: '/skills/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthMessageIndexRoute = AuthMessageIndexImport.update({
  path: '/message/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthJoboffersIndexRoute = AuthJoboffersIndexImport.update({
  path: '/joboffers/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthContactsIndexRoute = AuthContactsIndexImport.update({
  path: '/contacts/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSkillsAddIndexRoute = AuthSkillsAddIndexImport.update({
  path: '/skills/add/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthJoboffersAddIndexRoute = AuthJoboffersAddIndexImport.update({
  path: '/joboffers/add/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthJoboffersIdIndexRoute = AuthJoboffersIdIndexImport.update({
  path: '/joboffers/$id/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthContactsAddIndexRoute = AuthContactsAddIndexImport.update({
  path: '/contacts/add/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthContactsIdIndexRoute = AuthContactsIdIndexImport.update({
  path: '/contacts/$id/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSkillsIdEditIndexRoute = AuthSkillsIdEditIndexImport.update({
  path: '/skills/$id/edit/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthJoboffersIdEditIndexRoute = AuthJoboffersIdEditIndexImport.update({
  path: '/joboffers/$id/edit/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthContactsIdEditIndexRoute = AuthContactsIdEditIndexImport.update({
  path: '/contacts/$id/edit/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthJoboffersIdEditStatusIndexRoute =
  AuthJoboffersIdEditStatusIndexImport.update({
    path: '/joboffers/$id/edit/status/',
    getParentRoute: () => AuthRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth/contacts/': {
      id: '/_auth/contacts/'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthContactsIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/joboffers/': {
      id: '/_auth/joboffers/'
      path: '/joboffers'
      fullPath: '/joboffers'
      preLoaderRoute: typeof AuthJoboffersIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/message/': {
      id: '/_auth/message/'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof AuthMessageIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/skills/': {
      id: '/_auth/skills/'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthSkillsIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/contacts/$id/': {
      id: '/_auth/contacts/$id/'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof AuthContactsIdIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/contacts/add/': {
      id: '/_auth/contacts/add/'
      path: '/contacts/add'
      fullPath: '/contacts/add'
      preLoaderRoute: typeof AuthContactsAddIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/joboffers/$id/': {
      id: '/_auth/joboffers/$id/'
      path: '/joboffers/$id'
      fullPath: '/joboffers/$id'
      preLoaderRoute: typeof AuthJoboffersIdIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/joboffers/add/': {
      id: '/_auth/joboffers/add/'
      path: '/joboffers/add'
      fullPath: '/joboffers/add'
      preLoaderRoute: typeof AuthJoboffersAddIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/skills/add/': {
      id: '/_auth/skills/add/'
      path: '/skills/add'
      fullPath: '/skills/add'
      preLoaderRoute: typeof AuthSkillsAddIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/contacts/$id/edit/': {
      id: '/_auth/contacts/$id/edit/'
      path: '/contacts/$id/edit'
      fullPath: '/contacts/$id/edit'
      preLoaderRoute: typeof AuthContactsIdEditIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/joboffers/$id/edit/': {
      id: '/_auth/joboffers/$id/edit/'
      path: '/joboffers/$id/edit'
      fullPath: '/joboffers/$id/edit'
      preLoaderRoute: typeof AuthJoboffersIdEditIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/skills/$id/edit/': {
      id: '/_auth/skills/$id/edit/'
      path: '/skills/$id/edit'
      fullPath: '/skills/$id/edit'
      preLoaderRoute: typeof AuthSkillsIdEditIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/joboffers/$id/edit/status/': {
      id: '/_auth/joboffers/$id/edit/status/'
      path: '/joboffers/$id/edit/status'
      fullPath: '/joboffers/$id/edit/status'
      preLoaderRoute: typeof AuthJoboffersIdEditStatusIndexImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthContactsIndexRoute: typeof AuthContactsIndexRoute
  AuthJoboffersIndexRoute: typeof AuthJoboffersIndexRoute
  AuthMessageIndexRoute: typeof AuthMessageIndexRoute
  AuthSkillsIndexRoute: typeof AuthSkillsIndexRoute
  AuthContactsIdIndexRoute: typeof AuthContactsIdIndexRoute
  AuthContactsAddIndexRoute: typeof AuthContactsAddIndexRoute
  AuthJoboffersIdIndexRoute: typeof AuthJoboffersIdIndexRoute
  AuthJoboffersAddIndexRoute: typeof AuthJoboffersAddIndexRoute
  AuthSkillsAddIndexRoute: typeof AuthSkillsAddIndexRoute
  AuthContactsIdEditIndexRoute: typeof AuthContactsIdEditIndexRoute
  AuthJoboffersIdEditIndexRoute: typeof AuthJoboffersIdEditIndexRoute
  AuthSkillsIdEditIndexRoute: typeof AuthSkillsIdEditIndexRoute
  AuthJoboffersIdEditStatusIndexRoute: typeof AuthJoboffersIdEditStatusIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthContactsIndexRoute: AuthContactsIndexRoute,
  AuthJoboffersIndexRoute: AuthJoboffersIndexRoute,
  AuthMessageIndexRoute: AuthMessageIndexRoute,
  AuthSkillsIndexRoute: AuthSkillsIndexRoute,
  AuthContactsIdIndexRoute: AuthContactsIdIndexRoute,
  AuthContactsAddIndexRoute: AuthContactsAddIndexRoute,
  AuthJoboffersIdIndexRoute: AuthJoboffersIdIndexRoute,
  AuthJoboffersAddIndexRoute: AuthJoboffersAddIndexRoute,
  AuthSkillsAddIndexRoute: AuthSkillsAddIndexRoute,
  AuthContactsIdEditIndexRoute: AuthContactsIdEditIndexRoute,
  AuthJoboffersIdEditIndexRoute: AuthJoboffersIdEditIndexRoute,
  AuthSkillsIdEditIndexRoute: AuthSkillsIdEditIndexRoute,
  AuthJoboffersIdEditStatusIndexRoute: AuthJoboffersIdEditStatusIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthRouteWithChildren
  '/': typeof AuthIndexRoute
  '/login': typeof LoginIndexRoute
  '/contacts': typeof AuthContactsIndexRoute
  '/joboffers': typeof AuthJoboffersIndexRoute
  '/message': typeof AuthMessageIndexRoute
  '/skills': typeof AuthSkillsIndexRoute
  '/contacts/$id': typeof AuthContactsIdIndexRoute
  '/contacts/add': typeof AuthContactsAddIndexRoute
  '/joboffers/$id': typeof AuthJoboffersIdIndexRoute
  '/joboffers/add': typeof AuthJoboffersAddIndexRoute
  '/skills/add': typeof AuthSkillsAddIndexRoute
  '/contacts/$id/edit': typeof AuthContactsIdEditIndexRoute
  '/joboffers/$id/edit': typeof AuthJoboffersIdEditIndexRoute
  '/skills/$id/edit': typeof AuthSkillsIdEditIndexRoute
  '/joboffers/$id/edit/status': typeof AuthJoboffersIdEditStatusIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginIndexRoute
  '/contacts': typeof AuthContactsIndexRoute
  '/joboffers': typeof AuthJoboffersIndexRoute
  '/message': typeof AuthMessageIndexRoute
  '/skills': typeof AuthSkillsIndexRoute
  '/contacts/$id': typeof AuthContactsIdIndexRoute
  '/contacts/add': typeof AuthContactsAddIndexRoute
  '/joboffers/$id': typeof AuthJoboffersIdIndexRoute
  '/joboffers/add': typeof AuthJoboffersAddIndexRoute
  '/skills/add': typeof AuthSkillsAddIndexRoute
  '/contacts/$id/edit': typeof AuthContactsIdEditIndexRoute
  '/joboffers/$id/edit': typeof AuthJoboffersIdEditIndexRoute
  '/skills/$id/edit': typeof AuthSkillsIdEditIndexRoute
  '/joboffers/$id/edit/status': typeof AuthJoboffersIdEditStatusIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/': typeof AuthIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_auth/contacts/': typeof AuthContactsIndexRoute
  '/_auth/joboffers/': typeof AuthJoboffersIndexRoute
  '/_auth/message/': typeof AuthMessageIndexRoute
  '/_auth/skills/': typeof AuthSkillsIndexRoute
  '/_auth/contacts/$id/': typeof AuthContactsIdIndexRoute
  '/_auth/contacts/add/': typeof AuthContactsAddIndexRoute
  '/_auth/joboffers/$id/': typeof AuthJoboffersIdIndexRoute
  '/_auth/joboffers/add/': typeof AuthJoboffersAddIndexRoute
  '/_auth/skills/add/': typeof AuthSkillsAddIndexRoute
  '/_auth/contacts/$id/edit/': typeof AuthContactsIdEditIndexRoute
  '/_auth/joboffers/$id/edit/': typeof AuthJoboffersIdEditIndexRoute
  '/_auth/skills/$id/edit/': typeof AuthSkillsIdEditIndexRoute
  '/_auth/joboffers/$id/edit/status/': typeof AuthJoboffersIdEditStatusIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/'
    | '/login'
    | '/contacts'
    | '/joboffers'
    | '/message'
    | '/skills'
    | '/contacts/$id'
    | '/contacts/add'
    | '/joboffers/$id'
    | '/joboffers/add'
    | '/skills/add'
    | '/contacts/$id/edit'
    | '/joboffers/$id/edit'
    | '/skills/$id/edit'
    | '/joboffers/$id/edit/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/contacts'
    | '/joboffers'
    | '/message'
    | '/skills'
    | '/contacts/$id'
    | '/contacts/add'
    | '/joboffers/$id'
    | '/joboffers/add'
    | '/skills/add'
    | '/contacts/$id/edit'
    | '/joboffers/$id/edit'
    | '/skills/$id/edit'
    | '/joboffers/$id/edit/status'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/'
    | '/login/'
    | '/_auth/contacts/'
    | '/_auth/joboffers/'
    | '/_auth/message/'
    | '/_auth/skills/'
    | '/_auth/contacts/$id/'
    | '/_auth/contacts/add/'
    | '/_auth/joboffers/$id/'
    | '/_auth/joboffers/add/'
    | '/_auth/skills/add/'
    | '/_auth/contacts/$id/edit/'
    | '/_auth/joboffers/$id/edit/'
    | '/_auth/skills/$id/edit/'
    | '/_auth/joboffers/$id/edit/status/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/login/"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/",
        "/_auth/contacts/",
        "/_auth/joboffers/",
        "/_auth/message/",
        "/_auth/skills/",
        "/_auth/contacts/$id/",
        "/_auth/contacts/add/",
        "/_auth/joboffers/$id/",
        "/_auth/joboffers/add/",
        "/_auth/skills/add/",
        "/_auth/contacts/$id/edit/",
        "/_auth/joboffers/$id/edit/",
        "/_auth/skills/$id/edit/",
        "/_auth/joboffers/$id/edit/status/"
      ]
    },
    "/_auth/": {
      "filePath": "_auth/index.tsx",
      "parent": "/_auth"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/_auth/contacts/": {
      "filePath": "_auth/contacts/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/joboffers/": {
      "filePath": "_auth/joboffers/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/message/": {
      "filePath": "_auth/message/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/skills/": {
      "filePath": "_auth/skills/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/contacts/$id/": {
      "filePath": "_auth/contacts/$id/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/contacts/add/": {
      "filePath": "_auth/contacts/add/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/joboffers/$id/": {
      "filePath": "_auth/joboffers/$id/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/joboffers/add/": {
      "filePath": "_auth/joboffers/add/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/skills/add/": {
      "filePath": "_auth/skills/add/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/contacts/$id/edit/": {
      "filePath": "_auth/contacts/$id/edit/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/joboffers/$id/edit/": {
      "filePath": "_auth/joboffers/$id/edit/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/skills/$id/edit/": {
      "filePath": "_auth/skills/$id/edit/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/joboffers/$id/edit/status/": {
      "filePath": "_auth/joboffers/$id/edit/status/index.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
